# Site settings
title: Henrique Oliveira
email: mail@henriqueoliveira.net
description: > # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.henriqueoliveira.net" # the base hostname & protocol for your site
github_username:  hjoliveira
linkedin_username: hjoliveira

# Build settings
markdown: kramdown

#kramdown:
#  input: GFM

exclude:
  - CNAME
  - README

gems:
  - jekyll-sitemap
